spring.application.name=automotive-service-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/automotive_ai_support
spring.datasource.username=root
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true